### ISSUE TITLE
cvc4 has been moved to stanford

### ISSUE THREAD

**Issue by WilliamCoding** [agra-uni-bremen/dependencies#15]
cvc4 has been moved to stanford: http://cvc4.cs.stanford.edu/
I failed to get cvc4.

**Comment by hoangmle** [comment]
Thanks for reporting! We are aware of the issue but have not yet come to fix it.
In the meantime, you might want to use the package cvc4-smtcomp2015-stable which is pulled from github and thus not affected by the server change.

**Comment by WilliamCoding** [comment]
thanks. :-)

**Comment by hoangmle** [comment]
the latest commit  d4f29a3 fixes the URL for cvc-unstable (which now downloads and builds latest-unstable.tar.gz from the Stanford server)
